### ISSUE TITLE
Using pyspotlight fails

### ISSUE THREAD

**Issue by jnehring** [aolieman/pyspotlight#3]
Hello,

I tried pyspotlight. First I installed it:

```
sudo pip3 install pyspotlight
```

I also tried just using pip, not pip3.

Then I ran the [example code](https://github.com/aolieman/pyspotlight#usage). It says 

```
ModuleNotFoundError: No module named 'spotlight'
```

Can you give me a hint whats wrong? I tried python 2.7 and python 3.7.

**Comment by aolieman** [comment]
`pyspotlight` should be compatible with both of the python versions you've tried.

The `ModuleNotFoundError` is very generic and indicates that you have not succeeded in installing this package for the python interpreters that you used to run the example code.

My first guess would be that you have installed an alternative python distribution (such as Anaconda), which is configured to be your default python interpreter. Any packages installed by your OS-provided `pip` (on Ubuntu?) would not be visible to the python interpreter that you are using.

Please provide the output of the following shell commands:
> $ `which python` (e.g. `/home/alex/.pyenv/shims/python`)
> $ `which pip` (e.g. `/home/alex/.pyenv/shims/pip`)

It could be helpful to do the same for `python3` and `pip3`. I'm expecting your python and pip binaries to be part of different distributions.

A workaround that might do the trick without knowing your specific problem:
> $ `$(which python3) -m pip install pyspotlight`

Please let me know how this goes for you.

**Comment by jnehring** [comment]
Thank you, using your hints I solved the problems myself. I ran python3 from anaconda, but installed the pip modules normal. So when I did not run python3 (from anaconda) but /usr/bin/python3.6 (from normal python) then it worked. Thank you very much :)
